[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
unchecked_cheatcode_artifacts = true

[profile.deploy]
optimizer = true
optimizer_runs = 999999

[fmt]
sort_imports = true
wrap_comments = true

remappings = [
    "@openzeppelin/contracts/security/ReentrancyGuard.sol=lib/openzeppelin-contracts/contracts/utils/ReentrancyGuard.sol",
]
