[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
unchecked_cheatcode_artifacts = true
evm_version="cancun"

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia = "https://sepolia.base.org/"
arbitrum_one = "https://arbitrum.llamarpc.com"

[etherscan]
unichain_sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
basescan_sepolia = { key = "${BASESCAN_API_KEY}" }
arbitrum_one = { key = "${ARBITRUM_API_KEY}" }
[fmt]
sort_imports = true
wrap_comments = true

[fuzz]
max_test_cases = 100   # Number of fuzz cases
