[profile.default]
src = "src"
out = "out"
libs = ["lib"]
unchecked_cheatcode_artifacts = true

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia = "https://sepolia.base.org/"

[etherscan]
unichain_sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
basescan_sepolia = { key = "${BASESCAN_API_KEY}" }

[fuzz]
max_test_cases = 100   # Number of fuzz cases
